service: default
runtime: nodejs12

handlers:
  - url: /favicon\.ico
    static_files: dist/immopricing-front/favicon.ico
    upload: dist/immopricing-front/favicon\.ico

  - url: /(.*\..*$)
    static_files: dist/immopricing-front/\1
    upload: dist/immopricing-front/(.*\..*$)

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: dist/immopricing-front/index.html
    upload: dist/immopricing-front/index\.html
